/**
 * Servra - OpenAPI + Scalar Plugin
 *
 * Exposes an OpenAPI JSON endpoint and a Scalar UI reference page.
 * Uses the built-in docs/OpenAPI generator (`app.getOpenApiSpec()`).
 */

import type { Handler, Plugin, LOAApp } from '../core/types';

export interface OpenApiScalarOptions {
  specPath?: string;
  referencePath?: string;
  title?: string;
  /**
   * URL for the Scalar browser bundle (loaded by clients).
   * Default uses jsDelivr.
   */
  scalarScriptUrl?: string;
  /**
   * When true, include non-OpenAPI keys generated by Servra docs.
   * Scalar typically ignores unknown keys, but default is strict OpenAPI.
   */
  includeServraExtensions?: boolean;
}

const DEFAULT_SCALAR_SCRIPT = 'https://cdn.jsdelivr.net/npm/@scalar/api-reference';

export function openApiScalar(options: OpenApiScalarOptions = {}): Plugin {
  const specPath = normalizePath(options.specPath ?? '/openapi.json');
  const referencePath = normalizePath(options.referencePath ?? '/scalar');
  const scalarScriptUrl = options.scalarScriptUrl ?? DEFAULT_SCALAR_SCRIPT;
  const title = options.title ?? 'Servra API Reference';
  const includeExtensions = options.includeServraExtensions ?? false;

  return {
    name: 'openapi-scalar',
    version: '1.0.0',
    register(app: LOAApp) {
      app.get(specPath, createSpecHandler(app, includeExtensions));
      app.get(referencePath, createScalarUiHandler({
        title,
        specUrl: specPath,
        scalarScriptUrl,
      }));
    },
  };
}

function createSpecHandler(app: LOAApp, includeExtensions: boolean): Handler {
  return (_req, res) => {
    const spec = app.getOpenApiSpec();
    const openapi = includeExtensions
      ? spec
      : {
          openapi: spec.openapi,
          info: spec.info,
          paths: spec.paths,
        };

    res
      .header('Cache-Control', 'no-store')
      .json(openapi);
  };
}

function createScalarUiHandler(options: {
  title: string;
  specUrl: string;
  scalarScriptUrl: string;
}): Handler {
  const trustedScript = cspSourceFromUrl(options.scalarScriptUrl);
  const csp = [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    `script-src 'self' 'unsafe-inline' ${trustedScript}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "connect-src 'self'",
    "frame-ancestors 'none'",
  ].join('; ');

  const html = buildScalarHtml({
    title: options.title,
    specUrl: options.specUrl,
    scalarScriptUrl: options.scalarScriptUrl,
  });

  return (_req, res) => {
    res
      .header('Cache-Control', 'no-store')
      .header('Content-Security-Policy', csp)
      .html(html);
  };
}

function buildScalarHtml(options: {
  title: string;
  specUrl: string;
  scalarScriptUrl: string;
}): string {
  const safeTitle = escapeHtml(options.title);
  const safeSpecUrl = escapeHtml(options.specUrl);
  const safeScript = escapeHtml(options.scalarScriptUrl);

  // Include both common integration patterns to maximize compatibility across Scalar versions.
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${safeTitle}</title>
    <style>
      html, body { height: 100%; margin: 0; }
      api-reference { display: block; height: 100%; }
    </style>
  </head>
  <body>
    <api-reference spec-url="${safeSpecUrl}"></api-reference>
    <script id="api-reference" data-url="${safeSpecUrl}"></script>
    <script src="${safeScript}"></script>
  </body>
</html>`;
}

function normalizePath(path: string): string {
  const trimmed = path.trim();
  if (!trimmed) return '/';
  const normalized = trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
  return normalized.length > 1 && normalized.endsWith('/') ? normalized.slice(0, -1) : normalized;
}

function cspSourceFromUrl(url: string): string {
  try {
    const parsed = new URL(url);
    return parsed.origin;
  } catch {
    return 'https://cdn.jsdelivr.net';
  }
}

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export default openApiScalar;

